name: Auto Test

on:
  push:

env:
  # Define environment variables for versions and URLs
  CUDA_VERSION_WINDOWS: "12.6.0"
  CUDA_BUILD_WINDOWS: "560.76"

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    # Download CUDA Toolkit Installer (Windows)
    - name: Download CUDA Toolkit Installer (Windows)
      shell: pwsh
      run: |
        $cuda_version = "${{ env.CUDA_VERSION_WINDOWS }}"
        $cuda_build = "${{ env.CUDA_BUILD_WINDOWS }}"
        $cuda_url = "https://developer.download.nvidia.com/compute/cuda/${cuda_version}/local_installers/cuda_${cuda_version}_${cuda_build}_windows.exe"
        Write-Output "Attempting to download CUDA Toolkit from $cuda_url"

        # Check URL Accessibility
        try {
          $response = Invoke-WebRequest -Uri $cuda_url -Method Head -UseBasicParsing -ErrorAction Stop
          Write-Output "URL exists. Proceeding with download."
        }
        catch {
          Write-Error "CUDA Toolkit installer not found at $cuda_url. Please verify the URL."
          exit 1
        }

        # Download the Installer
        Invoke-WebRequest -Uri $cuda_url -OutFile "cuda_installer.exe" -UseBasicParsing

    # Install CUDA Toolkit (Windows)
    - name: Install CUDA Toolkit (Windows)
      shell: pwsh
      run: |
        Start-Process -FilePath "cuda_installer.exe" -ArgumentList "/S" -Wait
        Remove-Item "cuda_installer.exe"

    # Verify CUDA Installation
    - name: Verify CUDA Installation
      shell: pwsh
      run: |
        nvcc --version

    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: c:\hostedtoolcache\windows\python\3.12.7\x64\lib\site-packages
        key: ${{ runner.os }}-pip-${{ hashFiles('tests/requirements-runner.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
        pip install -r tests/requirements-runner.txt

    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel

    - name: Install the package
      run: |
        Get-ChildItem -Path dist -Filter *.whl | ForEach-Object { pip install $_.FullName }

    - name: Run video processing test
      run: |
        cd tests/python
        python test2.py
        python test3.py
